### ISSUE TITLE
Unable to install on Mac M1(Sonoma 14.3.1)

### ISSUE THREAD

**Issue by MaheshRathod4** [skiptools/skip#204]
![Screenshot 2024-08-23 at 6 47 57 PM](https://github.com/user-attachments/assets/e9e65323-5693-4328-be91-25ecaec48288)

**Comment by marcprux** [comment]
Is this an older Homebrew installation held over from a previous Intel mac? The error about "not built for the x86_64 CPU architecture" makes me suspect that even though you are on an M1, the Homebrew installation is an Intel one. 

`which brew` should return `/opt/homebrew/bin/brew` if it is the M1/ARM version.  If not, re-installing from https://brew.sh should fix the problem, but let us know if the issue persists.

**Comment by MaheshRathod4** [comment]
![Screenshot 2024-08-27 at 11 51 39 AM](https://github.com@marcprux user-attachments/assets/e5edad61-785d-4535-9271-440dfafa061c)

![Screenshot 2024-08-27 at 11 51 42 AM](https://github.com/user-attachments/assets/cde96694-476a-4060-bd35-54528a780a09)

@marcprux I have installed tried both the commands  **brew update** and install commands but still facing same issue

**Comment by MaheshRathod4** [comment]
![Screenshot 2024-08-27 at 11 55 38 AM](https://github.com/user-attachments/assets/186cac8f-57e9-43c4-bf65-e2b72b3c5ed1)

**Comment by marcprux** [comment]
What does `which brew` report? If it is `/usr/local/bin/brew`, then you are still using the Intel version, and you should delete it and re-install Homebrew from scratch as per https://brew.sh

**Comment by marcprux** [comment]
Very odd. You are using the M1 version of Homebrew, but it appears to be trying to install the x86 version of a dependency.

Can you try completely uninstalling Homebrew from the machine as per: https://github.com/homebrew/install#uninstall-homebrew

Once it has been removed, re-install it from scratch as per: https://github.com/homebrew/install#install-homebrew-on-macos-or-linux

And finally, try installing Skip again: `brew install skiptools/skip/skip`

Let us know if you still get the error…

**Comment by marcprux** [comment]
Closing for now because we believe this was addressed, but feel free to re-open if there is more information.
